[package]
name = "css-lens-wasm"
version = "0.1.0"
authors = ["poteboy <poteboy.dev@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]

[dependencies]
wasm-bindgen = "0.2.84"
lazy_static = "1.4.0"
regex = "1.10.5"
serde = "1.0.198"
serde-wasm-bindgen = "0.6.5"
serde_json = "1.0.116"
web-sys = {"version" = "0.3.44", features=['console']}
tsify = "0.4.5"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
